require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrokersController do

  # This should return the minimal set of attributes required to create a valid
  # Broker. As you add validations to Broker, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrokersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all brokers as @brokers" do
      broker = Broker.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brokers).should eq([broker])
    end
  end

  describe "GET show" do
    it "assigns the requested broker as @broker" do
      broker = Broker.create! valid_attributes
      get :show, {:id => broker.to_param}, valid_session
      assigns(:broker).should eq(broker)
    end
  end

  describe "GET new" do
    it "assigns a new broker as @broker" do
      get :new, {}, valid_session
      assigns(:broker).should be_a_new(Broker)
    end
  end

  describe "GET edit" do
    it "assigns the requested broker as @broker" do
      broker = Broker.create! valid_attributes
      get :edit, {:id => broker.to_param}, valid_session
      assigns(:broker).should eq(broker)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Broker" do
        expect {
          post :create, {:broker => valid_attributes}, valid_session
        }.to change(Broker, :count).by(1)
      end

      it "assigns a newly created broker as @broker" do
        post :create, {:broker => valid_attributes}, valid_session
        assigns(:broker).should be_a(Broker)
        assigns(:broker).should be_persisted
      end

      it "redirects to the created broker" do
        post :create, {:broker => valid_attributes}, valid_session
        response.should redirect_to(Broker.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved broker as @broker" do
        # Trigger the behavior that occurs when invalid params are submitted
        Broker.any_instance.stub(:save).and_return(false)
        post :create, {:broker => {}}, valid_session
        assigns(:broker).should be_a_new(Broker)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Broker.any_instance.stub(:save).and_return(false)
        post :create, {:broker => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested broker" do
        broker = Broker.create! valid_attributes
        # Assuming there are no other brokers in the database, this
        # specifies that the Broker created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Broker.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => broker.to_param, :broker => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested broker as @broker" do
        broker = Broker.create! valid_attributes
        put :update, {:id => broker.to_param, :broker => valid_attributes}, valid_session
        assigns(:broker).should eq(broker)
      end

      it "redirects to the broker" do
        broker = Broker.create! valid_attributes
        put :update, {:id => broker.to_param, :broker => valid_attributes}, valid_session
        response.should redirect_to(broker)
      end
    end

    describe "with invalid params" do
      it "assigns the broker as @broker" do
        broker = Broker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Broker.any_instance.stub(:save).and_return(false)
        put :update, {:id => broker.to_param, :broker => {}}, valid_session
        assigns(:broker).should eq(broker)
      end

      it "re-renders the 'edit' template" do
        broker = Broker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Broker.any_instance.stub(:save).and_return(false)
        put :update, {:id => broker.to_param, :broker => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested broker" do
      broker = Broker.create! valid_attributes
      expect {
        delete :destroy, {:id => broker.to_param}, valid_session
      }.to change(Broker, :count).by(-1)
    end

    it "redirects to the brokers list" do
      broker = Broker.create! valid_attributes
      delete :destroy, {:id => broker.to_param}, valid_session
      response.should redirect_to(brokers_url)
    end
  end

end
