require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InsurersController do

  # This should return the minimal set of attributes required to create a valid
  # Insurer. As you add validations to Insurer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsurersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all insurers as @insurers" do
      insurer = Insurer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:insurers).should eq([insurer])
    end
  end

  describe "GET show" do
    it "assigns the requested insurer as @insurer" do
      insurer = Insurer.create! valid_attributes
      get :show, {:id => insurer.to_param}, valid_session
      assigns(:insurer).should eq(insurer)
    end
  end

  describe "GET new" do
    it "assigns a new insurer as @insurer" do
      get :new, {}, valid_session
      assigns(:insurer).should be_a_new(Insurer)
    end
  end

  describe "GET edit" do
    it "assigns the requested insurer as @insurer" do
      insurer = Insurer.create! valid_attributes
      get :edit, {:id => insurer.to_param}, valid_session
      assigns(:insurer).should eq(insurer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Insurer" do
        expect {
          post :create, {:insurer => valid_attributes}, valid_session
        }.to change(Insurer, :count).by(1)
      end

      it "assigns a newly created insurer as @insurer" do
        post :create, {:insurer => valid_attributes}, valid_session
        assigns(:insurer).should be_a(Insurer)
        assigns(:insurer).should be_persisted
      end

      it "redirects to the created insurer" do
        post :create, {:insurer => valid_attributes}, valid_session
        response.should redirect_to(Insurer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insurer as @insurer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Insurer.any_instance.stub(:save).and_return(false)
        post :create, {:insurer => {}}, valid_session
        assigns(:insurer).should be_a_new(Insurer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Insurer.any_instance.stub(:save).and_return(false)
        post :create, {:insurer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested insurer" do
        insurer = Insurer.create! valid_attributes
        # Assuming there are no other insurers in the database, this
        # specifies that the Insurer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Insurer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => insurer.to_param, :insurer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested insurer as @insurer" do
        insurer = Insurer.create! valid_attributes
        put :update, {:id => insurer.to_param, :insurer => valid_attributes}, valid_session
        assigns(:insurer).should eq(insurer)
      end

      it "redirects to the insurer" do
        insurer = Insurer.create! valid_attributes
        put :update, {:id => insurer.to_param, :insurer => valid_attributes}, valid_session
        response.should redirect_to(insurer)
      end
    end

    describe "with invalid params" do
      it "assigns the insurer as @insurer" do
        insurer = Insurer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Insurer.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurer.to_param, :insurer => {}}, valid_session
        assigns(:insurer).should eq(insurer)
      end

      it "re-renders the 'edit' template" do
        insurer = Insurer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Insurer.any_instance.stub(:save).and_return(false)
        put :update, {:id => insurer.to_param, :insurer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insurer" do
      insurer = Insurer.create! valid_attributes
      expect {
        delete :destroy, {:id => insurer.to_param}, valid_session
      }.to change(Insurer, :count).by(-1)
    end

    it "redirects to the insurers list" do
      insurer = Insurer.create! valid_attributes
      delete :destroy, {:id => insurer.to_param}, valid_session
      response.should redirect_to(insurers_url)
    end
  end

end
